name: Run Tests
on: [push]
jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13, 3.14]
    steps:
      - uses: actions/checkout@v6
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          pip install --group test .
      - name: Verify with flake8
        run: |
          flake8 . --show-source
      - name: Run pytest
        run: |
          pytest
      - name: Run deptry
        run: |
          deptry .
